spring:
  application:
    name: currency-exchange

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/currencyexchange;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

external-service:
  nbp:
    url: http://api.nbp.pl/api
